services:
  meetuper_db:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - ./.data/pg/mount:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
