services:
  meetuper_db:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./.data/pg/mount:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  meetuper_redis:
    image: redis:alpine
    restart: always

  meetuper_backend:
    image: puddington/meetuper:latest
    restart: always
    depends_on:
      meetuper_db:
        condition: service_healthy
      meetuper_redis:
        condition: service_started
    env_file:
      - .env

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.meetuper.rule=Host(`meetuper.site`)"
      - "traefik.http.routers.meetuper.entrypoints=websecure"
      - "traefik.http.routers.meetuper.tls.certresolver=myresolver"
      - "traefik.http.services.meetuper.loadbalancer.server.port=9090"

    networks:
      - default
      - web

  meetuper_dbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    volumes:
      - ./.data/cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.cloudbeaver.rule=Host(`db.meetuper.site`)"
      - "traefik.http.routers.cloudbeaver.entrypoints=websecure"
      - "traefik.http.routers.cloudbeaver.tls.certresolver=myresolver"
      - "traefik.http.services.cloudbeaver.loadbalancer.server.port=8978"

networks:
  web:
    external: true
