// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/auth_password.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/auth_password.go -destination=internal/repo/mocks/auth_password_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/puddingtonnn/offlinemeetup_backend/internal/cache"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordUserRepository is a mock of PasswordUserRepository interface.
type MockPasswordUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordUserRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordUserRepositoryMockRecorder is the mock recorder for MockPasswordUserRepository.
type MockPasswordUserRepositoryMockRecorder struct {
	mock *MockPasswordUserRepository
}

// NewMockPasswordUserRepository creates a new mock instance.
func NewMockPasswordUserRepository(ctrl *gomock.Controller) *MockPasswordUserRepository {
	mock := &MockPasswordUserRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordUserRepository) EXPECT() *MockPasswordUserRepositoryMockRecorder {
	return m.recorder
}

// AttachPassword mocks base method.
func (m *MockPasswordUserRepository) AttachPassword(ctx context.Context, userID int64, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachPassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachPassword indicates an expected call of AttachPassword.
func (mr *MockPasswordUserRepositoryMockRecorder) AttachPassword(ctx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachPassword", reflect.TypeOf((*MockPasswordUserRepository)(nil).AttachPassword), ctx, userID, passwordHash)
}

// CreateUserWithPassword mocks base method.
func (m *MockPasswordUserRepository) CreateUserWithPassword(ctx context.Context, email, username, passwordHash string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithPassword", ctx, email, username, passwordHash)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserWithPassword indicates an expected call of CreateUserWithPassword.
func (mr *MockPasswordUserRepositoryMockRecorder) CreateUserWithPassword(ctx, email, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithPassword", reflect.TypeOf((*MockPasswordUserRepository)(nil).CreateUserWithPassword), ctx, email, username, passwordHash)
}

// FindIDByEmail mocks base method.
func (m *MockPasswordUserRepository) FindIDByEmail(ctx context.Context, email string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIDByEmail", ctx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIDByEmail indicates an expected call of FindIDByEmail.
func (mr *MockPasswordUserRepositoryMockRecorder) FindIDByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIDByEmail", reflect.TypeOf((*MockPasswordUserRepository)(nil).FindIDByEmail), ctx, email)
}

// FindIDByUsername mocks base method.
func (m *MockPasswordUserRepository) FindIDByUsername(ctx context.Context, username string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIDByUsername", ctx, username)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIDByUsername indicates an expected call of FindIDByUsername.
func (mr *MockPasswordUserRepositoryMockRecorder) FindIDByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIDByUsername", reflect.TypeOf((*MockPasswordUserRepository)(nil).FindIDByUsername), ctx, username)
}

// MockAuthStore is a mock of AuthStore interface.
type MockAuthStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuthStoreMockRecorder
	isgomock struct{}
}

// MockAuthStoreMockRecorder is the mock recorder for MockAuthStore.
type MockAuthStoreMockRecorder struct {
	mock *MockAuthStore
}

// NewMockAuthStore creates a new mock instance.
func NewMockAuthStore(ctrl *gomock.Controller) *MockAuthStore {
	mock := &MockAuthStore{ctrl: ctrl}
	mock.recorder = &MockAuthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthStore) EXPECT() *MockAuthStoreMockRecorder {
	return m.recorder
}

// CheckAndSetMailCooldown mocks base method.
func (m *MockAuthStore) CheckAndSetMailCooldown(ctx context.Context, email string, cooldown time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndSetMailCooldown", ctx, email, cooldown)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAndSetMailCooldown indicates an expected call of CheckAndSetMailCooldown.
func (mr *MockAuthStoreMockRecorder) CheckAndSetMailCooldown(ctx, email, cooldown any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndSetMailCooldown", reflect.TypeOf((*MockAuthStore)(nil).CheckAndSetMailCooldown), ctx, email, cooldown)
}

// CheckAndSetMailResetCooldown mocks base method.
func (m *MockAuthStore) CheckAndSetMailResetCooldown(ctx context.Context, email string, cooldown time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndSetMailResetCooldown", ctx, email, cooldown)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAndSetMailResetCooldown indicates an expected call of CheckAndSetMailResetCooldown.
func (mr *MockAuthStoreMockRecorder) CheckAndSetMailResetCooldown(ctx, email, cooldown any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndSetMailResetCooldown", reflect.TypeOf((*MockAuthStore)(nil).CheckAndSetMailResetCooldown), ctx, email, cooldown)
}

// DeletePendingReg mocks base method.
func (m *MockAuthStore) DeletePendingReg(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingReg", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingReg indicates an expected call of DeletePendingReg.
func (mr *MockAuthStoreMockRecorder) DeletePendingReg(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingReg", reflect.TypeOf((*MockAuthStore)(nil).DeletePendingReg), ctx, email)
}

// DeletePendingReset mocks base method.
func (m *MockAuthStore) DeletePendingReset(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingReset", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingReset indicates an expected call of DeletePendingReset.
func (mr *MockAuthStoreMockRecorder) DeletePendingReset(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingReset", reflect.TypeOf((*MockAuthStore)(nil).DeletePendingReset), ctx, email)
}

// GetPendingReg mocks base method.
func (m *MockAuthStore) GetPendingReg(ctx context.Context, email string) (cache.PendingReg, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingReg", ctx, email)
	ret0, _ := ret[0].(cache.PendingReg)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPendingReg indicates an expected call of GetPendingReg.
func (mr *MockAuthStoreMockRecorder) GetPendingReg(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingReg", reflect.TypeOf((*MockAuthStore)(nil).GetPendingReg), ctx, email)
}

// GetPendingReset mocks base method.
func (m *MockAuthStore) GetPendingReset(ctx context.Context, email string) (cache.PendingReg, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingReset", ctx, email)
	ret0, _ := ret[0].(cache.PendingReg)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPendingReset indicates an expected call of GetPendingReset.
func (mr *MockAuthStoreMockRecorder) GetPendingReset(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingReset", reflect.TypeOf((*MockAuthStore)(nil).GetPendingReset), ctx, email)
}

// IncrementLoginFail mocks base method.
func (m *MockAuthStore) IncrementLoginFail(ctx context.Context, login string, window time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementLoginFail", ctx, login, window)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementLoginFail indicates an expected call of IncrementLoginFail.
func (mr *MockAuthStoreMockRecorder) IncrementLoginFail(ctx, login, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementLoginFail", reflect.TypeOf((*MockAuthStore)(nil).IncrementLoginFail), ctx, login, window)
}

// IncrementMailQuota mocks base method.
func (m *MockAuthStore) IncrementMailQuota(ctx context.Context, email string, window time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementMailQuota", ctx, email, window)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementMailQuota indicates an expected call of IncrementMailQuota.
func (mr *MockAuthStoreMockRecorder) IncrementMailQuota(ctx, email, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementMailQuota", reflect.TypeOf((*MockAuthStore)(nil).IncrementMailQuota), ctx, email, window)
}

// IncrementMailResetQuota mocks base method.
func (m *MockAuthStore) IncrementMailResetQuota(ctx context.Context, email string, window time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementMailResetQuota", ctx, email, window)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementMailResetQuota indicates an expected call of IncrementMailResetQuota.
func (mr *MockAuthStoreMockRecorder) IncrementMailResetQuota(ctx, email, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementMailResetQuota", reflect.TypeOf((*MockAuthStore)(nil).IncrementMailResetQuota), ctx, email, window)
}

// IncrementPendingRegAttempts mocks base method.
func (m *MockAuthStore) IncrementPendingRegAttempts(ctx context.Context, email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPendingRegAttempts", ctx, email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementPendingRegAttempts indicates an expected call of IncrementPendingRegAttempts.
func (mr *MockAuthStoreMockRecorder) IncrementPendingRegAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPendingRegAttempts", reflect.TypeOf((*MockAuthStore)(nil).IncrementPendingRegAttempts), ctx, email)
}

// IncrementPendingResetAttempts mocks base method.
func (m *MockAuthStore) IncrementPendingResetAttempts(ctx context.Context, email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPendingResetAttempts", ctx, email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementPendingResetAttempts indicates an expected call of IncrementPendingResetAttempts.
func (mr *MockAuthStoreMockRecorder) IncrementPendingResetAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPendingResetAttempts", reflect.TypeOf((*MockAuthStore)(nil).IncrementPendingResetAttempts), ctx, email)
}

// ResetLoginFail mocks base method.
func (m *MockAuthStore) ResetLoginFail(ctx context.Context, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetLoginFail", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetLoginFail indicates an expected call of ResetLoginFail.
func (mr *MockAuthStoreMockRecorder) ResetLoginFail(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetLoginFail", reflect.TypeOf((*MockAuthStore)(nil).ResetLoginFail), ctx, login)
}

// SavePendingReg mocks base method.
func (m *MockAuthStore) SavePendingReg(ctx context.Context, email string, data cache.PendingReg, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePendingReg", ctx, email, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePendingReg indicates an expected call of SavePendingReg.
func (mr *MockAuthStoreMockRecorder) SavePendingReg(ctx, email, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePendingReg", reflect.TypeOf((*MockAuthStore)(nil).SavePendingReg), ctx, email, data, ttl)
}

// SavePendingReset mocks base method.
func (m *MockAuthStore) SavePendingReset(ctx context.Context, email string, data cache.PendingReg, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePendingReset", ctx, email, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePendingReset indicates an expected call of SavePendingReset.
func (mr *MockAuthStoreMockRecorder) SavePendingReset(ctx, email, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePendingReset", reflect.TypeOf((*MockAuthStore)(nil).SavePendingReset), ctx, email, data, ttl)
}

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMailer) Send(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMailerMockRecorder) Send(ctx, to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMailer)(nil).Send), ctx, to, subject, body)
}
