// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/auth_login.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/auth_login.go -destination=internal/repo/mocks/auth_login_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialsRepository is a mock of CredentialsRepository interface.
type MockCredentialsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialsRepositoryMockRecorder is the mock recorder for MockCredentialsRepository.
type MockCredentialsRepositoryMockRecorder struct {
	mock *MockCredentialsRepository
}

// NewMockCredentialsRepository creates a new mock instance.
func NewMockCredentialsRepository(ctrl *gomock.Controller) *MockCredentialsRepository {
	mock := &MockCredentialsRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepository) EXPECT() *MockCredentialsRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCredentialsRepository) Get(ctx context.Context, userID int64) (*domain.UserCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*domain.UserCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCredentialsRepositoryMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCredentialsRepository)(nil).Get), ctx, userID)
}
