// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/chat.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/chat.go -destination=internal/repo/mocks/chat_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockChatRepository is a mock of ChatRepository interface.
type MockChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryMockRecorder
	isgomock struct{}
}

// MockChatRepositoryMockRecorder is the mock recorder for MockChatRepository.
type MockChatRepositoryMockRecorder struct {
	mock *MockChatRepository
}

// NewMockChatRepository creates a new mock instance.
func NewMockChatRepository(ctrl *gomock.Controller) *MockChatRepository {
	mock := &MockChatRepository{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepository) EXPECT() *MockChatRepositoryMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockChatRepository) AddParticipant(ctx context.Context, tx bun.IDB, chatParticipant *domain.ChatParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", ctx, tx, chatParticipant)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockChatRepositoryMockRecorder) AddParticipant(ctx, tx, chatParticipant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockChatRepository)(nil).AddParticipant), ctx, tx, chatParticipant)
}

// CreateGroupChat mocks base method.
func (m *MockChatRepository) CreateGroupChat(ctx context.Context, tx bun.IDB, chat *domain.Chat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupChat", ctx, tx, chat)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroupChat indicates an expected call of CreateGroupChat.
func (mr *MockChatRepositoryMockRecorder) CreateGroupChat(ctx, tx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupChat", reflect.TypeOf((*MockChatRepository)(nil).CreateGroupChat), ctx, tx, chat)
}

// DeleteMessage mocks base method.
func (m *MockChatRepository) DeleteMessage(ctx context.Context, chatID, msgID, editorID int64) (int64, []int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, chatID, msgID, editorID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockChatRepositoryMockRecorder) DeleteMessage(ctx, chatID, msgID, editorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockChatRepository)(nil).DeleteMessage), ctx, chatID, msgID, editorID)
}

// EditMessage mocks base method.
func (m *MockChatRepository) EditMessage(ctx context.Context, chatID, msgID, editorID int64, content string) (*domain.Message, []int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessage", ctx, chatID, msgID, editorID, content)
	ret0, _ := ret[0].(*domain.Message)
	ret1, _ := ret[1].([]int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockChatRepositoryMockRecorder) EditMessage(ctx, chatID, msgID, editorID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockChatRepository)(nil).EditMessage), ctx, chatID, msgID, editorID, content)
}

// GetChatByMeetupID mocks base method.
func (m *MockChatRepository) GetChatByMeetupID(ctx context.Context, tx bun.IDB, meetupID int64) (*domain.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatByMeetupID", ctx, tx, meetupID)
	ret0, _ := ret[0].(*domain.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatByMeetupID indicates an expected call of GetChatByMeetupID.
func (mr *MockChatRepositoryMockRecorder) GetChatByMeetupID(ctx, tx, meetupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatByMeetupID", reflect.TypeOf((*MockChatRepository)(nil).GetChatByMeetupID), ctx, tx, meetupID)
}

// GetChatParticipantIDs mocks base method.
func (m *MockChatRepository) GetChatParticipantIDs(ctx context.Context, chatID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatParticipantIDs", ctx, chatID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatParticipantIDs indicates an expected call of GetChatParticipantIDs.
func (mr *MockChatRepositoryMockRecorder) GetChatParticipantIDs(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatParticipantIDs", reflect.TypeOf((*MockChatRepository)(nil).GetChatParticipantIDs), ctx, chatID)
}

// GetCoChatUserIDs mocks base method.
func (m *MockChatRepository) GetCoChatUserIDs(ctx context.Context, userID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoChatUserIDs", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoChatUserIDs indicates an expected call of GetCoChatUserIDs.
func (mr *MockChatRepositoryMockRecorder) GetCoChatUserIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoChatUserIDs", reflect.TypeOf((*MockChatRepository)(nil).GetCoChatUserIDs), ctx, userID)
}

// GetMessages mocks base method.
func (m *MockChatRepository) GetMessages(ctx context.Context, userID, chatID, cursor int64, limit int) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, userID, chatID, cursor, limit)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockChatRepositoryMockRecorder) GetMessages(ctx, userID, chatID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockChatRepository)(nil).GetMessages), ctx, userID, chatID, cursor, limit)
}

// GetUserChats mocks base method.
func (m *MockChatRepository) GetUserChats(ctx context.Context, userID int64) ([]domain.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChats", ctx, userID)
	ret0, _ := ret[0].([]domain.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChats indicates an expected call of GetUserChats.
func (mr *MockChatRepositoryMockRecorder) GetUserChats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChats", reflect.TypeOf((*MockChatRepository)(nil).GetUserChats), ctx, userID)
}

// MarkAsRead mocks base method.
func (m *MockChatRepository) MarkAsRead(ctx context.Context, chatID, userID, lastReadMessageID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, chatID, userID, lastReadMessageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockChatRepositoryMockRecorder) MarkAsRead(ctx, chatID, userID, lastReadMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockChatRepository)(nil).MarkAsRead), ctx, chatID, userID, lastReadMessageID)
}

// SaveMessage mocks base method.
func (m *MockChatRepository) SaveMessage(ctx context.Context, msg *domain.Message) (*domain.Message, []int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, msg)
	ret0, _ := ret[0].(*domain.Message)
	ret1, _ := ret[1].([]int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockChatRepositoryMockRecorder) SaveMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockChatRepository)(nil).SaveMessage), ctx, msg)
}
