// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/file.go
//
// Generated by this command:
//
//	mockgen -source=internal/repo/file.go -destination=internal/repo/mocks/file_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
