// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/meetup.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/meetup.go -destination=internal/repo/mocks/meetup_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	dto "github.com/puddingtonnn/offlinemeetup_backend/internal/transport/http/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockMeetupRepository is a mock of MeetupRepository interface.
type MockMeetupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMeetupRepositoryMockRecorder
	isgomock struct{}
}

// MockMeetupRepositoryMockRecorder is the mock recorder for MockMeetupRepository.
type MockMeetupRepositoryMockRecorder struct {
	mock *MockMeetupRepository
}

// NewMockMeetupRepository creates a new mock instance.
func NewMockMeetupRepository(ctrl *gomock.Controller) *MockMeetupRepository {
	mock := &MockMeetupRepository{ctrl: ctrl}
	mock.recorder = &MockMeetupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeetupRepository) EXPECT() *MockMeetupRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMeetupRepository) Create(ctx context.Context, meetup *domain.Meetup, chat *domain.Chat, tagIDs []int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, meetup, chat, tagIDs)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMeetupRepositoryMockRecorder) Create(ctx, meetup, chat, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMeetupRepository)(nil).Create), ctx, meetup, chat, tagIDs)
}

// Delete mocks base method.
func (m *MockMeetupRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMeetupRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMeetupRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMeetupRepository) GetByID(ctx context.Context, id, currentUserID int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, currentUserID)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMeetupRepositoryMockRecorder) GetByID(ctx, id, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMeetupRepository)(nil).GetByID), ctx, id, currentUserID)
}

// GetByInviteToken mocks base method.
func (m *MockMeetupRepository) GetByInviteToken(ctx context.Context, token uuid.UUID, currentUserID int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteToken", ctx, token, currentUserID)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteToken indicates an expected call of GetByInviteToken.
func (mr *MockMeetupRepositoryMockRecorder) GetByInviteToken(ctx, token, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteToken", reflect.TypeOf((*MockMeetupRepository)(nil).GetByInviteToken), ctx, token, currentUserID)
}

// Join mocks base method.
func (m *MockMeetupRepository) Join(ctx context.Context, meetupID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, meetupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockMeetupRepositoryMockRecorder) Join(ctx, meetupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockMeetupRepository)(nil).Join), ctx, meetupID, userID)
}

// Leave mocks base method.
func (m *MockMeetupRepository) Leave(ctx context.Context, meetupID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", ctx, meetupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Leave indicates an expected call of Leave.
func (mr *MockMeetupRepositoryMockRecorder) Leave(ctx, meetupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockMeetupRepository)(nil).Leave), ctx, meetupID, userID)
}

// List mocks base method.
func (m *MockMeetupRepository) List(ctx context.Context, filter dto.MeetupFilter, currentUserID int64) ([]domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, currentUserID)
	ret0, _ := ret[0].([]domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMeetupRepositoryMockRecorder) List(ctx, filter, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMeetupRepository)(nil).List), ctx, filter, currentUserID)
}

// Update mocks base method.
func (m *MockMeetupRepository) Update(ctx context.Context, meetup *domain.Meetup, newTagIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, meetup, newTagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMeetupRepositoryMockRecorder) Update(ctx, meetup, newTagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMeetupRepository)(nil).Update), ctx, meetup, newTagIDs)
}
