// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/user.go
//
// Generated by this command:
//
//	mockgen -source=internal/repo/user.go -destination=internal/repo/mocks/user_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
