// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/profile.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/profile.go -destination=internal/service/mocks/profile_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileRepository is a mock of ProfileRepository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockProfileRepository) GetByUserID(ctx context.Context, userID int64) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockProfileRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockProfileRepository)(nil).GetByUserID), ctx, userID)
}

// UpdateProfile mocks base method.
func (m *MockProfileRepository) UpdateProfile(ctx context.Context, profile *domain.Profile) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, profile)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileRepositoryMockRecorder) UpdateProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileRepository)(nil).UpdateProfile), ctx, profile)
}

// MockUserTagUpdater is a mock of UserTagUpdater interface.
type MockUserTagUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockUserTagUpdaterMockRecorder
	isgomock struct{}
}

// MockUserTagUpdaterMockRecorder is the mock recorder for MockUserTagUpdater.
type MockUserTagUpdaterMockRecorder struct {
	mock *MockUserTagUpdater
}

// NewMockUserTagUpdater creates a new mock instance.
func NewMockUserTagUpdater(ctrl *gomock.Controller) *MockUserTagUpdater {
	mock := &MockUserTagUpdater{ctrl: ctrl}
	mock.recorder = &MockUserTagUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTagUpdater) EXPECT() *MockUserTagUpdaterMockRecorder {
	return m.recorder
}

// GetTagsByUserID mocks base method.
func (m *MockUserTagUpdater) GetTagsByUserID(ctx context.Context, userID int64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByUserID indicates an expected call of GetTagsByUserID.
func (mr *MockUserTagUpdaterMockRecorder) GetTagsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByUserID", reflect.TypeOf((*MockUserTagUpdater)(nil).GetTagsByUserID), ctx, userID)
}

// UpdateTags mocks base method.
func (m *MockUserTagUpdater) UpdateTags(ctx context.Context, userID int64, tagIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTags", ctx, userID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTags indicates an expected call of UpdateTags.
func (mr *MockUserTagUpdaterMockRecorder) UpdateTags(ctx, userID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTags", reflect.TypeOf((*MockUserTagUpdater)(nil).UpdateTags), ctx, userID, tagIDs)
}
