name: Deploy Meetuper

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Добавил возможность ручного запуска для тестов

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/meetuper

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/root/my-go-app/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }}} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
            
            cd /root/my-go-app
            
            docker compose pull meetuper_backend
            
            docker compose up -d
            
            docker image prune -f